name: todolist1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.1
  firebase_auth:
  firebase_core: ^1.24.0
  http: ^0.13.4
  badges: ^2.0.2
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  readmore: ^2.1.0
  curved_navigation_bar: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
